
services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: news_aggregator
        volumes:
            - .:/var/www
        working_dir: /var/www
        ports:
            - "9000:9000"
        depends_on:
            - mysql
            - redis

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: news_aggregator
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "33066:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    redis:
        image: redis:alpine
        container_name: laravel_redis
        ports:
            - "6379:6379"

    scheduler:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        command: php artisan schedule:work
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - app

    queue:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        command: php artisan horizon
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - app


volumes:
    dbdata:
